
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author ABDULLAH
 */
public class Hangman extends javax.swing.JFrame {
    // Inheritance from the Jframe class
    /**
     * Creates new form GuessTheWordGame
     */
    public Hangman() {
        initComponents();
        setWordToGui();
    }

    private final String[] wordindex = new String[]{"elephant", "javascript", "technology", "education", "maximum", "overslept"};
    int randomNum = (int) (Math.random() * wordindex.length);
    private final String word = wordindex[randomNum];
    private char[] wordLetter = new char[word.length()];
    private char[] letterDisplayed = new char[10];

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel = new javax.swing.JPanel();
        Buttonicon = new javax.swing.JButton();
        c2 = new javax.swing.JLabel();
        c3 = new javax.swing.JLabel();
        c4 = new javax.swing.JLabel();
        c5 = new javax.swing.JLabel();
        c6 = new javax.swing.JLabel();
        c7 = new javax.swing.JLabel();
        c8 = new javax.swing.JLabel();
        c9 = new javax.swing.JLabel();
        c10 = new javax.swing.JLabel();
        c1 = new javax.swing.JLabel();
        inputletter = new javax.swing.JTextField();
        incorrect = new javax.swing.JLabel();
        btntry = new javax.swing.JButton();
        lblanswer = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Hangman");
        setBackground(new java.awt.Color(0, 0, 0));
        setResizable(false);

        panel.setBackground(new java.awt.Color(255, 255, 255));

        Buttonicon.setBackground(new java.awt.Color(255, 255, 255));
        Buttonicon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Start.png"))); // NOI18N
        Buttonicon.setToolTipText("Do not let the stick man get hanged.");
        Buttonicon.setContentAreaFilled(false);

        c2.setText("X");

        c3.setText("X");

        c4.setText("X");

        c5.setText("X");

        c6.setText("X");

        c7.setText("X");

        c8.setText("X");

        c9.setText("X");

        c10.setText("X");

        c1.setText("X");

        inputletter.setToolTipText("Enter the letter you want to check here.");
        inputletter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputletterActionPerformed(evt);
            }
        });

        incorrect.setText("0");
        incorrect.setToolTipText("This shows the number of incorrect letters you have entered.");

        btntry.setText("Try Letter");
        btntry.setToolTipText("Click here to check whether the letter you entered in the above text fied is correct.");
        btntry.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btntryActionPerformed(evt);
            }
        });

        lblanswer.setText("Incorrect Attempts");

        javax.swing.GroupLayout panelLayout = new javax.swing.GroupLayout(panel);
        panel.setLayout(panelLayout);
        panelLayout.setHorizontalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelLayout.createSequentialGroup()
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelLayout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(inputletter)
                            .addGroup(panelLayout.createSequentialGroup()
                                .addComponent(c1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(c2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(c3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(c4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(c5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(c6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(c7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(c8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(c9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(c10))))
                    .addGroup(panelLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblanswer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btntry, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(panelLayout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addComponent(incorrect, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(Buttonicon)
                .addContainerGap(24, Short.MAX_VALUE))
        );
        panelLayout.setVerticalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLayout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(c2)
                    .addComponent(c3)
                    .addComponent(c4)
                    .addComponent(c5)
                    .addComponent(c6)
                    .addComponent(c7)
                    .addComponent(c8)
                    .addComponent(c9)
                    .addComponent(c10)
                    .addComponent(c1))
                .addGap(47, 47, 47)
                .addComponent(inputletter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(54, 54, 54)
                .addComponent(lblanswer)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(incorrect)
                .addGap(43, 43, 43)
                .addComponent(btntry)
                .addContainerGap(184, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(Buttonicon))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void setWordToGui() {
        //Seperate the letteres in the word and add them to an array called word letter.
        for (int i = 0; i < word.length(); i++) {
            wordLetter[i] = word.substring(i, i + 1).toUpperCase().charAt(0);
        }
        //Add X's in the GUI based on the length of the word.
        for (int i = 0; i < word.length(); i++) {
            letterDisplayed[i] = 'X';
        }
        initializeGuiCharValues();
    }

    public void initializeGuiCharValues() {
        c1.setText(Character.toString(letterDisplayed[0]));
        c2.setText(Character.toString(letterDisplayed[1]));
        c3.setText(Character.toString(letterDisplayed[2]));
        c4.setText(Character.toString(letterDisplayed[3]));
        c5.setText(Character.toString(letterDisplayed[4]));
        c6.setText(Character.toString(letterDisplayed[5]));
        c7.setText(Character.toString(letterDisplayed[6]));
        c8.setText(Character.toString(letterDisplayed[7]));
        c9.setText(Character.toString(letterDisplayed[8]));
        c10.setText(Character.toString(letterDisplayed[9]));
    }

    public boolean isValidTextFieldValue() {
        String textFieldValue = inputletter.getText().toLowerCase();
        int ascii = (int) textFieldValue.charAt(0);
        if (ascii >= 97 && ascii <= 122 && textFieldValue.length() == 1) {
            return true;
        } else {
            return false;
        }
    }

    private void btntryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btntryActionPerformed
        try {
            boolean valid = isValidTextFieldValue();
            if (valid) {
                boolean letterFound = false;
                char letter = inputletter.getText().toUpperCase().charAt(0);
                for (int i = 0; i < word.length(); i++) {
                    if (wordLetter[i] == letter) {
                        letterDisplayed[i] = letter;
                        letterFound = true;
                    }
                }
                if (!letterFound) {
                    int wrong = Integer.parseInt(incorrect.getText());
                    wrong++;
                    incorrect.setText(Integer.toString(wrong));
                    switch (wrong) {
                        case 1:
                            Buttonicon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/guess1.png")));
                            break;
                        case 2:
                            Buttonicon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/guess2.png")));
                            break;
                        case 3:
                            Buttonicon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/guess3.png")));
                            break;
                        case 4:
                            Buttonicon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/guess4.png")));
                            break;
                        case 5:
                            Buttonicon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/guess5.png")));
                            break;
                        case 6:
                            Buttonicon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/FinalGuess.png")));
                            JOptionPane.showMessageDialog(null, "You lost the game. The word you were trying to guess was \"" + word + "\"", "You Lost", WIDTH);
                            System.exit(0);
                            break;
                        default:
                            break;      
                    }
                }
                initializeGuiCharValues();
            } else {
                JOptionPane.showMessageDialog(null, "You have entered an invalid value, please re-enter the character", "Error: Invalid Character", WIDTH);
            }
            boolean wordSolved = false;
            for (int i = 0; i < word.length(); i++) {
                if (letterDisplayed[i] == wordLetter[i]) {
                    wordSolved = true;
                } else {
                    wordSolved = false;
                    break;
                }
            }
            if (wordSolved) {
                JOptionPane.showMessageDialog(null, "You won the game, Congratulations, ", "You Win", WIDTH);
                System.exit(0);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e, "Oops , Try again", WIDTH);
        }
    }//GEN-LAST:event_btntryActionPerformed

    private void inputletterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputletterActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputletterActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Hangman.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Hangman.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Hangman.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Hangman.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Hangman().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Buttonicon;
    private javax.swing.JButton btntry;
    private javax.swing.JLabel c1;
    private javax.swing.JLabel c10;
    private javax.swing.JLabel c2;
    private javax.swing.JLabel c3;
    private javax.swing.JLabel c4;
    private javax.swing.JLabel c5;
    private javax.swing.JLabel c6;
    private javax.swing.JLabel c7;
    private javax.swing.JLabel c8;
    private javax.swing.JLabel c9;
    private javax.swing.JLabel incorrect;
    private javax.swing.JTextField inputletter;
    private javax.swing.JLabel lblanswer;
    private javax.swing.JPanel panel;
    // End of variables declaration//GEN-END:variables
}
